development: &default
  city_name: 'Austin'
  state_name: 'Texas'
  country_name: 'United States'
  lat: 30.2545168
  lon: -97.7442346
  radius: 100
  units: mi
  site_name: 'SXSW Civic Hackathon'
  daily_vote_limit: 5
  geolocate_enabled: false
  default_user_lat: 30.2545168
  default_user_lon: -97.7442346
  points: 
    support_issue: 1
    report_issue: 5
    other_supports_issue: 1
    close_issue: 1
    closed_report_one_week: 2
    closed_report_one_month: 3 
    other_supports_supported_issue: 1
    suggest_solution: 1
    support_solution: 1
    other_supports_suggested_solution: 1
    credited_solution_on_close: 3
    tweet_clickthrough: 1
    vote_on_solution: 5
  awards: 

test: &test
  <<: *default

production: 
  <<: *default
  
cucumber:
  <<: *test
